---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nfs-vols.yaml
  - ../sources
  - ../base/hajimari.yaml
  - ./plex
  - ./jellyfin
  - ./syncthing
  - ./tautulli
  - ./zoneminder
