---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./discord-secret.yaml
  - ./cf-secret.yaml
  - ../base
  - ./longhorn
  - ./cert-manager
  - ./local-path-provisioner
  - ../extras/intel-device-plugin
  - ../extras/cloudnative-pg-operator
  - ../extras/kubernetes-dashboard
