---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - ../base/whoami.yaml
  - ./nfs-videos-vols.yaml
  - ./deesl
  - ./audiobookshelf
  - ./deluge
  - ./frigate
  - ./grafana
  - ./homeassistant
  - ./jellyfin
  - ./seerr
  - ./mosquitto
  - ./nextcloud
  - ./pg-cluster
  - ./prowlarr
  - ./radarr
  - ./sonarr
  - ./unpackerr
  - ./wizarr
  - ./zigbee2mqtt
