---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - ../base/whoami.yaml
  - ./audiobookshelf
  - ./homeassistant
  - ./mosquitto
  - ./unpackerr
  - ./zigbee2mqtt
  - ./pg-cluster
