---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ext
  namespace: default
  annotations:
    hajimari.io/icon: mdi:home-assistant
spec:
  ingressClassName: nginx
  rules:
    - host: homeassistant.oaklodge.dev
      http:
        paths:
          - backend:
              service:
                name: homeassistant-ext
                port:
                  number: 8123
            path: /
            pathType: Prefix
